# Generated by Django 5.0.7 on 2024-08-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso_info',
            new_name='Course_info',
        ),
        migrations.RenameModel(
            old_name='Cursos_Page',
            new_name='Course_List',
        ),
    ]
