# Generated by Django 5.0.7 on 2024-08-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesAPI', '0002_rename_curso_info_course_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_list',
            name='image',
            field=models.URLField(),
        ),
    ]
