# Generated by Django 5.0.7 on 2024-08-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos_Page',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=350)),
                ('opinions', models.CharField(max_length=250)),
                ('valuation', models.FloatField()),
                ('count_mod', models.IntegerField()),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APICursos.cursos_page')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APICursos.curso_info')),
            ],
        ),
    ]
