# Generated by Django 5.0.7 on 2024-08-18 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos_page',
            old_name='course_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='curso_info',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='APICursos.cursos_page'),
        ),
    ]
